# Basic site settings
title: "*C"
description: "I'm a BITer, and this is my personal page."
lang: en-GB
encoding: utf-8
baseurl: ""
email: "zhouxc26@gmail.com"
repo: "https://github.com/zhouxc26"

# Theme settings
logo: "/assets/logos/logo.ico"
css_inline: true

# Navigation
navigation_header:
- title: Home
  url: /

navigation_footer:
- title: Repository link
  url: https://github.com/zhouxc26/zhouxc26.github.io

# Social and sharing
social_links:
  GitHub: https://github.com/zhouxc26

sharing_links:
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Favicons
favicons:
  16: '/assets/logos/logo.ico'
  32: '/assets/logos/logo.ico'
  96: '/assets/logos/logo.ico'
  120: '/assets/logos/logo.ico'
  144: '/assets/logos/logo.ico'
  180: '/assets/logos/logo.ico'
  512: '/assets/logos/logo.ico'
  1024: '/assets/logos/logo.ico'

# Jekyll settings
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Europe/London

# Collections and defaults
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

# Build settings
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# Fonts
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap

# Plugin settings
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
